In [ ]:
!gdown --id 1UhIF3TqmBxWGJIj6vNsYUx0iLiNnOd0q

/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1UhIF3TqmBxWGJIj6vNsYUx0iLiNnOd0q
To: /content/train.csv
100% 18.3M/18.3M [00:00<00:00, 125MB/s]


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
train_df = pd.read_csv('train.csv')
train_df.dropna(inplace =True) 

In [ ]:
train_df.head()

text dialect
0  قولتله اصلي عياده الدكتور اهيه فوقينا    اتكسف...      EG
1  متحاولش تبقي مبهور بحد مشفتوش وهو بياكل وهو صا...      EG
2  كنك متردش عليا ؟   والله كنت ماسك النقال وشفت ...      LY
3                                بتزيح او بقعد بحضنك      LB
4  مفيش حد كامل من كل شء مفيش حد مش بيغلط مغيش حد...      EG

In [ ]:
max_sequence_len = 0
for sentence in train_df.text:
    max_sequence_len = max(len(sentence), max_sequence_len)
print(max_sequence_len)

284


In [ ]:
import tensorflow as tf
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from numpy import array
import gensim
from gensim.models import KeyedVectors
from gensim.models import word2vec

In [ ]:
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print('encoded_docs:\n',encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, 
padding='post')
print('padded_docs:\n',padded_docs)

encoded_docs:
 [[2, 3, 4], [5, 1, 6], [7], [1, 8], [9, 10, 11], [12, 13, 14, 15], [16, 17], [2, 1, 18]]
padded_docs:
 [[ 2  3  4  0]
 [ 5  1  6  0]
 [ 7  0  0  0]
 [ 1  8  0  0]
 [ 9 10 11  0]
 [12 13 14 15]
 [16 17  0  0]
 [ 2  1 18  0]]


In [ ]:
import tensorflow as tf
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from numpy import array
import gensim
from gensim.models import KeyedVectors
from gensim.models import word2vec

In [ ]:
train_df.head()

text dialect
0  قولتله اصلي عياده الدكتور اهيه فوقينا    اتكسف...      EG
1  متحاولش تبقي مبهور بحد مشفتوش وهو بياكل وهو صا...      EG
2  كنك متردش عليا ؟   والله كنت ماسك النقال وشفت ...      LY
3                                بتزيح او بقعد بحضنك      LB
4  مفيش حد كامل من كل شء مفيش حد مش بيغلط مغيش حد...      EG

In [ ]:
import tensorflow_hub as hub


In [ ]:
import numpy as np
import pandas as pd
import tensorflow_hub as hub
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM

In [ ]:
max_sequence_len = 100


In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('CAMeL-Lab/bert-base-arabic-camelbert-da-sentiment')


Some weights of the model checkpoint at /root/.cache/torch/sentence_transformers/CAMeL-Lab_bert-base-arabic-camelbert-da-sentiment were not used when initializing BertModel: ['classifier.bias', 'classifier.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
x12=  x_train.iloc[0]

'الفكره انو ما بعرف ليه صرختي؟ نفس الشي انت وياها لا رح تسممك و    اه لا ممكن انت تسمميها'

In [ ]:
from sklearn.preprocessing import LabelEncoder


# initialize a LabelEncoder object
le = LabelEncoder()

# apply label encoding to the 'color' column
train_df['dialect_index'] = le.fit_transform(train_df['dialect'])

train_df

text dialect  \
0       قولتله اصلي عياده الدكتور اهيه فوقينا    اتكسف...      EG   
1       متحاولش تبقي مبهور بحد مشفتوش وهو بياكل وهو صا...      EG   
2       كنك متردش عليا ؟   والله كنت ماسك النقال وشفت ...      LY   
3                                     بتزيح او بقعد بحضنك      LB   
4       مفيش حد كامل من كل شء مفيش حد مش بيغلط مغيش حد...      EG   
...                                                   ...     ...   
132855                    مش عاملها فولو شو طلعها بخلقتي؟      LB   
132856  يضطر يقفل الملف و يوديه للمراجعه    و تنتظر لم...      EG   
132857  حزب اللات ماهدد حدا بس الكل صاروا فدا صرمايه ا...      LB   
132858                               كده ما كترت المحلبيه      SD   
132859                             فنان ومبدع   يسعد مساك      LB   

        dialect_index  
0                   0  
1                   0  
2                   2  
3                   1  
4                   0  
...               ...  
132855              1  
132856              0  
132857              1  
132858              4  
132859              1  

[132859 rows x 3 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(train_df.text, train_df.dialect_index, test_size=0.1, random_state=42)

In [ ]:
import gensim

w2v_model = gensim.models.Word2Vec(X_train,
                                   vector_size=100,
                                   window=5,
                                   min_count=2)

# Replace the words in each text message with the learned word vector
words = set(w2v_model.wv.index_to_key)
X_train_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])
                         for ls in X_train])
X_test_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])
                         for ls in X_test])

<ipython-input-14-8c95dcb7b7e7>:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_train_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])
<ipython-input-14-8c95dcb7b7e7>:12: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_test_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])


In [ ]:
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense

# Define the RNN model architecture
model = Sequential()
#model.add(Embedding(input_dim=len(w2v_model.wv.index_to_key), output_dim=100))
model.add(Embedding(len(w2v_model.wv.index_to_key)+1, 32))
model.add(LSTM(32, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2)) 
model.add(Dense(5, activation='softmax'))
model.summary()
# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model using Word2Vec embeddings as input and dialect labels as output


Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, None, 32)          2240      
                                                                 
 lstm_6 (LSTM)               (None, 32)                8320      
                                                                 
 dense_9 (Dense)             (None, 32)                1056      
                                                                 
 dense_10 (Dense)            (None, 32)                1056      
                                                                 
 dropout_3 (Dropout)         (None, 32)                0         
                                                                 
 dense_11 (Dense)            (None, 5)                 165       
                                                                 
Total params: 12,837
Trainable params: 12,837
Non-trai

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
class TokenizerWrapper(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.tokenizer = Tokenizer()
    
    def fit(self, X, y=None):
        self.tokenizer.fit_on_texts(X)
        return self
    
    def transform(self, X, y=None):
        X_seq = self.tokenizer.texts_to_sequences(X)
        X_seq_padded = pad_sequences(X_seq, 100)
        return X_seq_padded


In [ ]:
model = Sequential()
model.add(Embedding(len(tokenizer.index_word)+1, 32))
model.add(LSTM(32, dropout=0.0, recurrent_dropout=0.0))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2)) 
model.add(Dense(5, activation='softmax'))
model.summary()
# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_15 (Embedding)    (None, None, 32)          6779488   
                                                                 
 lstm_15 (LSTM)              (None, 32)                8320      
                                                                 
 dense_34 (Dense)            (None, 32)                1056      
                                                                 
 dense_35 (Dense)            (None, 32)                1056      
                                                                 
 dropout_9 (Dropout)         (None, 32)                0         
                                                                 
 dense_36 (Dense)            (None, 5)                 165       
                                                                 
Total params: 6,790,085
Trainable params: 6,790,085
N

In [ ]:
# create the pipeline
pipeline = make_pipeline(TokenizerWrapper(), model)

# fit the pipeline to the training data
from tensorflow.keras.callbacks import EarlyStopping
#pipeline.set_params(epochs=10)

#early_stop = EarlyStopping(monitor='val_loss', patience=3)
#pipeline.set_params(sequential__epochs  = 10)
pipeline.fit(X_train, y_train)



In [ ]:
y_prop = pipeline.predict(X_test)
y_pred = np.argmax(y_prop , axis = -1)

416/416 [==============================] - 10s 25ms/step


In [ ]:

# Evaluate the performance of the pipeline on the test set
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print("Accuracy:", accuracy_score(y_test, y_pred))


Accuracy: 0.8204124642480807


In [ ]:
# pipeline.write().overwrite().save("pipline.h5")


In [ ]:
import joblib

joblib.dump(pipeline, 'DL1_pipeline.pkl')

['my_pipeline.pkl']

In [ ]:
import numpy as np
y_prob = model.predict(X_test_seq_padded, verbose=0)
y_pred = np.argmax(y_prob, axis=-1)

In [ ]:
decoded_labels = encoder.inverse_transform(y_pred)

# print the decoded labels
print(decoded_labels)

In [ ]:
from sklearn.metrics import classification_report


report = classification_report(y_test, y_pred)
print(report)

#print("accuracy: {:0.3f}".format(metrics.accuracy_score(y_test, y_pred)))

              precision    recall  f1-score   support

           0       0.86      0.86      0.86      5156
           1       0.82      0.84      0.83      2550
           2       0.79      0.79      0.79      3299
           3       0.77      0.68      0.72       958
           4       0.66      0.66      0.66      1323

    accuracy                           0.81     13286
   macro avg       0.78      0.77      0.77     13286
weighted avg       0.81      0.81      0.81     13286



In [ ]:
model1 = Sequential()

model.add(Embedding(len(tokenizer.index_word)+1, 32))
# add the first hidden layer with 64 units and input dimension of 100
model.add(LSTM(32, dropout=0, recurrent_dropout=0))

model1.add(Dense(128, activation='relu'))

model1.add(Dense(64, activation='relu'))
model1.add(Dense(64, activation='relu'))
# add the second hidden layer with 32 units
model1.add(Dense(32, activation='relu'))

# add the third hidden layer with 16 units
model1.add(Dense(16, activation='relu'))
model.add(Dropout(0.2))
# add the output layer with 1 unit and sigmoid activation function
model1.add(Dense(5, activation='softmax'))

# compile the model with binary crossentropy loss function and Adam optimizer
model1.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
history1 = model1.fit(X_train_seq_padded, y_train, 
                    batch_size=32, epochs=10,
                    validation_data=(X_test_seq_padded, y_test))

Epoch 1/10
3737/3737 [==============================] - 17s 4ms/step - loss: 15.4346 - accuracy: 0.3840 - val_loss: 1.4536 - val_accuracy: 0.3881
Epoch 2/10
3737/3737 [==============================] - 14s 4ms/step - loss: 1.4535 - accuracy: 0.3903 - val_loss: 1.4496 - val_accuracy: 0.3881
Epoch 3/10
3737/3737 [==============================] - 14s 4ms/step - loss: 1.4523 - accuracy: 0.3903 - val_loss: 1.4499 - val_accuracy: 0.3881
Epoch 4/10
3737/3737 [==============================] - 15s 4ms/step - loss: 1.4525 - accuracy: 0.3903 - val_loss: 1.4496 - val_accuracy: 0.3881
Epoch 5/10
3737/3737 [==============================] - 14s 4ms/step - loss: 1.4523 - accuracy: 0.3903 - val_loss: 1.4498 - val_accuracy: 0.3881
Epoch 6/10
3737/3737 [==============================] - 14s 4ms/step - loss: 1.4524 - accuracy: 0.3903 - val_loss: 1.4499 - val_accuracy: 0.3881
Epoch 7/10
3737/3737 [==============================] - 15s 4ms/step - loss: 1.4524 - accuracy: 0.3903 - val_loss: 1.4499 - val_a